# ----------------------------------------
# General
# output directory for processed data
base: 
  "/home/groups/dsfisher/icvijovic/tonsil-spatial/data"
workflow_dir: "/home/groups/dsfisher/icvijovic/tonsil-spatial/snakemake_workflow" 

  
# human or mouse
species: human
# partition (for cluster computing)
partition: "owners"

# Software
#---------------------------
vdj_scripts: "scripts"
grmlin: "/home/users/cvijovic/grmlin/grmlin" 
#
#references
#------------
vdj_ref_prefix: "vdj_human"
vdj_reference: "/home/groups/quake/mswift/5prime_10X_workflow/db/vdj_reference"
inner_primers: "/home/groups/quake/mswift/tabula-bursa/snakemake_workflow/db/inner_primers.txt"
10X_transcriptome: "https://cf.10xgenomics.com/supp/cell-exp/refdata-gex-GRCh38-2020-A.tar.gz"
transcriptome: "/home/groups/quake/mswift/tabula-bursa/snakemake_workflow/db/refdata-gex-GRCh38-2020-A"
#10X cell barcode whitelist
whitelist: "db/whitelists/737K-august-2016.txt"
# the assembly pipeline uses the immcantation framework for IgBLAST
# options: 'docker' or 'singularity'
container_type: singularity
# STAR alignment: fasta and gtf files
# (these should not need to be changed)
ighc_db:
  human: db/IGHC/human_IGHC_IMGT_membrane_only_reformatted.fasta
  imgt_exons: db/IGHC/IGHC_exons.bed
  imgt_introns: db/IGHC/IGHC_introns_inner.bed
  mouse: db/IGHC/mouse_IGHC_IMGT_reformatted.fast
# Igblast
IGDBDIR: /oak/stanford/groups/quake/shared/TabulaBursa/igblast
